# Generated by Django 5.0.6 on 2024-12-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0007_remove_workspace_pages_remove_tag_pages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('message', models.TextField(max_length=2000)),
                ('msg_type', models.CharField(choices=[('client', 'Client'), ('server', 'Server')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='chat.chat')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='workspace.workspace')),
            ],
        ),
    ]
