# Generated by Django 5.1.2 on 2024-11-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_note_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='notes',
        ),
        migrations.AddField(
            model_name='tag',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='tags', to='workspace.page'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
