# Generated by Django 5.0.6 on 2024-12-28 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='end_date',
        ),
        migrations.AddField(
            model_name='plan',
            name='ai_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_collaborator_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_notes_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_workspaces_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='note_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='workspace_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
