# Generated by Django 5.0.6 on 2025-01-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_remove_plan_created_at_remove_plan_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='note_count',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='workspace_count',
        ),
    ]
