# Generated by Django 5.0.6 on 2024-12-28 08:43
from django.db import migrations

def create_default_plan(apps, schema_editor):
    Plan = apps.get_model('plan', 'Plan')
    if not Plan.objects.filter(is_default=True).exists():
        Plan.objects.create(
            name="Free Plan",
            description="Default free plan for all users.",
            price=0.0,
            is_default=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_is_default'),
    ]

    operations = [
        migrations.RunPython(create_default_plan),
    ]
